[package]
name = "huffman_coding"
version = "0.1.0"
authors = ["glugg23 <m.leonhardt424@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.1"
byteorder = "1.3"
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
